_BASE_: "../Base-RCNN-VGG16.yaml"
OUTPUT_DIR: "./output/C2F_0.02"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: ""
  LABLED_WEIGHTS: "/mnt/csip-113/PETS/source/C2F.pth"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    NUM_CLASSES: 8
    LOSS: "FocalLoss" # variant: "CrossEntropy", FocalLoss
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  EPOCHS: 10
  Period: 1
  WARM_UP_EPOCH: 2
  BASE_LR: 0.0008
  IMG_PER_BATCH_UNLABEL: 4 # k8925
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_UNLABEL: ("cityscapes_foggy_train_0.02_1",)
  TEST: ("cityscapes_foggy_val_0.02_1",)
SFDA:
  Trainer: "dateacher"
  BBOX_THRESHOLD: 0.5
  TEACHER_UPDATE_ITER: 2
  EMA_KEEP_RATE_dynamic: 0.9996
  UNSUP_LOSS_WEIGHT: 2.0
  PSEUDO_THRESHOLD: 0.5
  UNSUP_ROI_LOSS_WEIGHT: 1.0
  UNSUP_RPN_LOSS_WEIGHT: 1.0
